<script type="text/javascript">
//<![CDATA[

var peLabelsFieldSet;

var initProductExplodedLabels = function(){

  require([
      "jquery",
      "jquery/ui",       
  ],function($) {

    peLabelsFieldSet = $('#pe_labels_init');

    var loadoptions = function(){
    
      if (peLabelsFieldSet.find('div').length > 0)
        return;

      $.ajax({
        type: 'POST',
        url: '<?php echo $this->getUrl('productexploded/pe_product_labels', array('_current' => true)); ?>',
        async: true,
        data: {isAjax:true, form_key: FORM_KEY},
        dataType: 'html',
        showLoader: true              
      }).done(function (result) {
        if (!result.error){      
          peLabelsFieldSet.html(result);              
        }        
      }).fail(function(xhr, status, error) {
        console.error("AJAX request failed: " + error);
      });
          
    }
    
    loadoptions();
    
    peLabelsFieldSet.closest('.admin__fieldset-wrapper-content').prev('.fieldset-wrapper-title').click(loadoptions);    
    
  });

};

//]]> 
</script>
